apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse_main
    isDefault: true
    jsonData:
      host: clickhouse
      port: 9000
      username: ${CLICKHOUSE_USER}
      defaultDatabase: ${CLICKHOUSE_DB}
      protocol: native
      secure: false
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD}
    editable: true
